Repository SEIIGruppe2/Server, pull requests merged in 2024-05, with the labels that each got.

#24 21 anpassen der spawnmonster klasse
  src/main/java/at/aau/se2/handler/game/GameHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/DrawCardHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/GameRoundHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/PlayerRollsDiceHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/RegisterUsernameHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/RequestUsernamesForSwitchHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/SpawnMonsterHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardDeckHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/TurnHandler.java
  src/main/java/at/aau/se2/model/Monster.java
  src/main/java/at/aau/se2/utils/Player.java
  src/test/java/at/aau/se2/handler/game/subhandlers/DrawCardHandlerTest.java
  src/test/java/at/aau/se2/handler/game/subhandlers/DummyHandlerImplTest.java
  src/test/java/at/aau/se2/handler/game/subhandlers/RequestUsernamesForSwitchHandlerTest.java
  src/test/java/at/aau/se2/handler/game/subhandlers/SpawnMonsterHandlerTest.java
  src/test/java/at/aau/se2/handler/game/subhandlers/SwitchCardDeckHandlerTest.java
  src/test/java/at/aau/se2/utils/PlayerTest.java
  src/test/java/at/aau/se2/utils/UtilityMethodsTest.java
Labels: enhancement

#30 29 customise the turnhandler method
  src/main/java/at/aau/se2/handler/game/GameHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/PlayerRollsDiceHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/RequestUsernamesHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/SpawnMonsterHandler.java
  src/main/java/at/aau/se2/handler/game/subhandlers/TurnHandler.java
Labels: enhancement

#32 25 monsterattackhandler
  .idea/misc.xml
  src/main/java/at/aau/se2/dto/MonsterAttackDTO.java
  src/main/java/at/aau/se2/handler/game/subhandlers/MonsterAttackHandler.java
  src/main/java/at/aau/se2/model/towers/TowerImpl.java
  src/main/java/at/aau/se2/service/MAHService.java
  src/test/java/at/aau/se2/dto/MonsterAttackDTOTest.java
  src/test/java/at/aau/se2/model/towers/TowerImplTest.java
  src/test/java/at/aau/se2/service/MAHServiceTest.java
Labels: enhancement, testing, refactoring

#36 35 hotfix monsterattack
  src/main/java/at/aau/se2/handler/game/subhandlers/MonsterAttackHandler.java
  src/main/java/at/aau/se2/service/MAHService.java
  src/main/java/at/aau/se2/utils/GameState.java
Labels: enhancement, refactoring
